swagger: "2.0"
info:
    title: Books Service
    description: Service for managing Books with CRUD operations.
    version: ""
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /book:
        post:
            tags:
                - librarian
            summary: create-book librarian
            description: Create a single book.
            operationId: librarian#create-book
            parameters:
                - name: Create-BookRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/LibrarianCreateBookRequestBody'
                    required:
                        - title
                        - author
                        - book_cover
                        - published_at
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/LibrarianCreateBookResponseBody'
            schemes:
                - http
        patch:
            tags:
                - librarian
            summary: update-book librarian
            description: Updates a book by the given id.
            operationId: librarian#update-book
            parameters:
                - name: Update-BookRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/LibrarianUpdateBookRequestBody'
                    required:
                        - title
                        - author
                        - book_cover
                        - published_at
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/LibrarianUpdateBookResponseBody'
            schemes:
                - http
    /book/{id}:
        get:
            tags:
                - librarian
            summary: get-book librarian
            description: Retrieve a book by id.
            operationId: librarian#get-book
            parameters:
                - name: id
                  in: path
                  description: Book id
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/LibrarianGetBookResponseBody'
            schemes:
                - http
        delete:
            tags:
                - librarian
            summary: delete-book librarian
            description: Delete a single book.
            operationId: librarian#delete-book
            parameters:
                - name: id
                  in: path
                  description: Book id
                  required: true
                  type: integer
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
    /books/{skip}/{take}:
        get:
            tags:
                - librarian
            summary: get-books librarian
            description: Get paginated books by specifying the number of books to skip and take.
            operationId: librarian#get-books
            parameters:
                - name: skip
                  in: path
                  description: Number of books to skip
                  required: true
                  type: integer
                - name: take
                  in: path
                  description: Number of books to take after skip
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/LibrarianGetBooksResponseBody'
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - librarian
            summary: Download ./gen/http/openapi.json
            operationId: librarian#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    LibrarianCreateBookRequestBody:
        title: LibrarianCreateBookRequestBody
        type: object
        properties:
            author:
                type: string
                description: The author of the book.
                example: 9vw
                minLength: 3
                maxLength: 100
            book_cover:
                type: string
                description: The cover image of the book.
                example: 1uj
                minLength: 15
                maxLength: 1024
            published_at:
                type: string
                description: The date at which the book was published.
                example: "1992-08-15"
                format: date
            title:
                type: string
                description: The title of the book.
                example: rc
                minLength: 1
                maxLength: 255
        example:
            author: "402"
            book_cover: 0vu
            published_at: "1979-06-05"
            title: t
        required:
            - title
            - author
            - book_cover
            - published_at
    LibrarianCreateBookResponseBody:
        title: 'Mediatype identifier: createbookresponse; view=default'
        type: object
        properties:
            author:
                type: string
                description: The author of the book.
                example: Amet eveniet voluptatibus est quo.
            book_cover:
                type: string
                description: The cover image of the book.
                example: Molestiae suscipit saepe minus consequatur suscipit molestiae.
            id:
                type: integer
                description: The unique id of the book.
                example: 1946582791838852945
                format: int64
            published_at:
                type: string
                description: The date at which the book was published.
                example: Quae consectetur nobis eveniet.
            title:
                type: string
                description: The title of the book.
                example: Iste incidunt ea temporibus blanditiis.
        description: Create-BookResponseBody result type (default view)
        example:
            author: Qui voluptas consectetur.
            book_cover: Aut aliquid ut laborum.
            id: 7645458295767987086
            published_at: Est rerum ad repudiandae excepturi occaecati.
            title: Labore alias.
        required:
            - id
            - title
            - book_cover
            - author
            - published_at
    LibrarianGetBookResponseBody:
        title: 'Mediatype identifier: getbookresponse; view=default'
        type: object
        properties:
            author:
                type: string
                description: The author of the book.
                example: Provident velit ad unde.
            book_cover:
                type: string
                description: The cover image of the book.
                example: Est enim explicabo.
            id:
                type: integer
                description: The unique id of the book.
                example: 1850134162586048436
                format: int64
            published_at:
                type: string
                description: The date at which the book was published.
                example: Eaque nostrum et sed dicta ab qui.
            title:
                type: string
                description: The title of the book.
                example: Illum optio illum laborum.
        description: Get-BookResponseBody result type (default view)
        example:
            author: Quidem laboriosam excepturi sunt molestiae voluptas.
            book_cover: Voluptatibus quo dolorum facere cupiditate.
            id: 4136957915571514672
            published_at: A est voluptatibus.
            title: At qui molestiae molestiae hic.
        required:
            - id
            - title
            - book_cover
            - author
            - published_at
    LibrarianGetBooksResponseBody:
        title: 'Mediatype identifier: getbooksresponse; view=default'
        type: object
        properties:
            books:
                $ref: '#/definitions/ResultbookResponseBodyCollection'
        description: Get-BooksResponseBody result type (default view)
        example:
            books:
                - author: Rerum reiciendis delectus eaque.
                  book_cover: Sit rem sequi quidem sint deleniti sed.
                  id: 7065326254943901839
                  published_at: Aut dolorem aut esse nulla nam.
                  title: Illum atque deserunt.
                - author: Rerum reiciendis delectus eaque.
                  book_cover: Sit rem sequi quidem sint deleniti sed.
                  id: 7065326254943901839
                  published_at: Aut dolorem aut esse nulla nam.
                  title: Illum atque deserunt.
                - author: Rerum reiciendis delectus eaque.
                  book_cover: Sit rem sequi quidem sint deleniti sed.
                  id: 7065326254943901839
                  published_at: Aut dolorem aut esse nulla nam.
                  title: Illum atque deserunt.
                - author: Rerum reiciendis delectus eaque.
                  book_cover: Sit rem sequi quidem sint deleniti sed.
                  id: 7065326254943901839
                  published_at: Aut dolorem aut esse nulla nam.
                  title: Illum atque deserunt.
    LibrarianUpdateBookRequestBody:
        title: LibrarianUpdateBookRequestBody
        type: object
        properties:
            author:
                type: string
                description: The author of the book.
                example: "403"
                minLength: 3
                maxLength: 100
            book_cover:
                type: string
                description: The cover image of the book.
                example: iqt
                minLength: 15
                maxLength: 1024
            id:
                type: integer
                description: The unique id of the book.
                example: 3207292315515913100
                minimum: 1
            published_at:
                type: string
                description: The date at which the book was published.
                example: "1982-08-06"
                format: date
            title:
                type: string
                description: The title of the book.
                example: "70"
                minLength: 1
                maxLength: 255
        example:
            author: ff7
            book_cover: a87
            id: 8621350514377074246
            published_at: "1978-12-04"
            title: "8"
        required:
            - title
            - author
            - book_cover
            - published_at
    LibrarianUpdateBookResponseBody:
        title: 'Mediatype identifier: updatebookresponse; view=default'
        type: object
        properties:
            author:
                type: string
                description: The author of the book.
                example: Ut cupiditate aut illum libero molestiae.
            book_cover:
                type: string
                description: The cover image of the book.
                example: Eaque adipisci autem molestiae beatae eos.
            id:
                type: integer
                description: The unique id of the book.
                example: 1256297072930731336
                format: int64
            published_at:
                type: string
                description: The date at which the book was published.
                example: Voluptatem et expedita aut vel natus.
            title:
                type: string
                description: The title of the book.
                example: Optio id et consectetur officiis culpa quisquam.
        description: Update-BookResponseBody result type (default view)
        example:
            author: Eos voluptatibus dolor inventore cumque.
            book_cover: Adipisci culpa et necessitatibus vitae.
            id: 67014572703103580
            published_at: Repudiandae voluptate ratione consectetur.
            title: Quos eum ducimus.
        required:
            - id
            - title
            - book_cover
            - author
            - published_at
    ResultbookResponseBody:
        title: 'Mediatype identifier: resultbook; view=default'
        type: object
        properties:
            author:
                type: string
                description: The author of the book.
                example: Sint provident quia enim soluta voluptatibus.
            book_cover:
                type: string
                description: The cover image of the book.
                example: Quidem magni quis.
            id:
                type: integer
                description: The unique id of the book.
                example: 3644640777498982687
                format: int64
            published_at:
                type: string
                description: The date at which the book was published.
                example: Voluptatum voluptas.
            title:
                type: string
                description: The title of the book.
                example: Cupiditate iste quia et.
        description: ResultbookResponseBody result type (default view)
        example:
            author: Qui ut tenetur voluptas corrupti suscipit.
            book_cover: Nulla omnis esse veritatis amet.
            id: 7637808607123294340
            published_at: Ea est quam itaque minima sit.
            title: Ad facilis molestiae commodi.
        required:
            - id
            - title
            - book_cover
            - author
            - published_at
    ResultbookResponseBodyCollection:
        title: 'Mediatype identifier: resultbook; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/ResultbookResponseBody'
        description: ResultbookCollectionResponseBody is the result type for an array of ResultbookResponseBody (default view)
        example:
            - author: Rerum reiciendis delectus eaque.
              book_cover: Sit rem sequi quidem sint deleniti sed.
              id: 7065326254943901839
              published_at: Aut dolorem aut esse nulla nam.
              title: Illum atque deserunt.
            - author: Rerum reiciendis delectus eaque.
              book_cover: Sit rem sequi quidem sint deleniti sed.
              id: 7065326254943901839
              published_at: Aut dolorem aut esse nulla nam.
              title: Illum atque deserunt.
