openapi: 3.0.3
info:
    title: Books Service
    description: Service for managing Books with CRUD operations.
    version: "1.0"
servers:
    - url: http://localhost:8000
paths:
    /book:
        patch:
            tags:
                - librarian
            summary: update-book librarian
            description: Updates a book by the given id.
            operationId: librarian#update-book
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateBookRequestBody'
                        example:
                            author: 94b
                            book_cover: op
                            id: 5920727773572055287
                            published_at: "1972-12-20"
                            title: "2"
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Updatebookresponse'
                            example:
                                author: Sint suscipit autem.
                                book_cover: Et perferendis doloribus rerum vitae at id.
                                id: 433367765525243458
                                published_at: Est illum quis exercitationem aperiam natus.
                                title: Quod aut nihil nesciunt blanditiis recusandae molestias.
        post:
            tags:
                - librarian
            summary: create-book librarian
            description: Create a single book.
            operationId: librarian#create-book
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateBookRequestBody'
                        example:
                            author: 17n
                            book_cover: l8
                            published_at: "1999-02-14"
                            title: e0
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Createbookresponse'
                            example:
                                author: Velit sit quis numquam aspernatur molestiae.
                                book_cover: Consequuntur minima earum.
                                id: 3521883182131032859
                                published_at: Qui eveniet quia.
                                title: Et in consectetur totam.
    /book/{id}:
        delete:
            tags:
                - librarian
            summary: delete-book librarian
            description: Delete a single book.
            operationId: librarian#delete-book
            parameters:
                - name: id
                  in: path
                  description: Book id
                  required: true
                  schema:
                    type: integer
                    description: Book id
                    example: 8671389531151817975
                    format: int64
                  example: 3792528279807343999
            responses:
                "204":
                    description: No Content response.
        get:
            tags:
                - librarian
            summary: get-book librarian
            description: Retrieve a book by id.
            operationId: librarian#get-book
            parameters:
                - name: id
                  in: path
                  description: The ID of the book.
                  required: true
                  schema:
                    type: integer
                    description: The ID of the book.
                    example: 803983059747621496
                    minimum: 1
                  example: 517088234167279133
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Getbookresponse'
                            example:
                                author: Blanditiis molestiae.
                                book_cover: Ut deleniti accusamus molestias in.
                                id: 2881518213516787023
                                published_at: Et autem earum harum occaecati sit eligendi.
                                title: Deleniti eligendi.
    /books/{skip}/{take}:
        get:
            tags:
                - librarian
            summary: get-books librarian
            description: Get paginated books by specifying the number of books to skip and take.
            operationId: librarian#get-books
            parameters:
                - name: skip
                  in: path
                  description: The numbers of records to skip before return.
                  required: true
                  schema:
                    type: integer
                    description: The numbers of records to skip before return.
                    example: 5575987020207916261
                    minimum: 0
                  example: 7765743731959460325
                - name: take
                  in: path
                  description: The numbers of records to return.
                  required: true
                  schema:
                    type: integer
                    description: The numbers of records to return.
                    example: 6296177713048552717
                    minimum: 1
                  example: 5445189832620645871
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Getbooksresponse'
                            example:
                                books:
                                    - author: Aut ut occaecati et et.
                                      book_cover: Sed tenetur qui quisquam qui.
                                      id: 3171323111833809843
                                      published_at: Ratione sapiente et provident dolorum amet labore.
                                      title: Et cumque velit ut quo ut.
                                    - author: Aut ut occaecati et et.
                                      book_cover: Sed tenetur qui quisquam qui.
                                      id: 3171323111833809843
                                      published_at: Ratione sapiente et provident dolorum amet labore.
                                      title: Et cumque velit ut quo ut.
    /openapi.json:
        get:
            tags:
                - librarian
            summary: Download ./gen/http/openapi.json
            operationId: librarian#/openapi.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        CreateBookRequestBody:
            type: object
            properties:
                author:
                    type: string
                    description: The author of the book.
                    example: obu
                    minLength: 3
                    maxLength: 100
                book_cover:
                    type: string
                    description: The URL to the cover image.
                    example: s
                    minLength: 1
                    maxLength: 2048
                published_at:
                    type: string
                    description: The date at which the book was published.
                    example: "1987-03-10"
                    format: date
                title:
                    type: string
                    description: The title of the book.
                    example: "5"
                    minLength: 1
                    maxLength: 255
            example:
                author: iwc
                book_cover: z
                published_at: "1992-05-04"
                title: s0
            required:
                - title
                - author
                - book_cover
                - published_at
        Createbookresponse:
            type: object
            properties:
                author:
                    type: string
                    description: The author of the book.
                    example: Dolorem neque illo.
                book_cover:
                    type: string
                    description: The cover image of the book.
                    example: Debitis sint est numquam ex at.
                id:
                    type: integer
                    description: The unique id of the book.
                    example: 3307113812017478415
                    format: int64
                published_at:
                    type: string
                    description: The date at which the book was published.
                    example: Nihil consectetur et voluptatem et voluptatem.
                title:
                    type: string
                    description: The title of the book.
                    example: Rerum nesciunt sed.
            example:
                author: Maiores eum magni in ipsam.
                book_cover: Ad nihil natus neque.
                id: 8385126137979667061
                published_at: Incidunt aut consequatur occaecati.
                title: Enim deleniti omnis dolores similique.
            required:
                - id
                - title
                - book_cover
                - author
                - published_at
        Getbookresponse:
            type: object
            properties:
                author:
                    type: string
                    description: The author of the book.
                    example: Inventore assumenda.
                book_cover:
                    type: string
                    description: The cover image of the book.
                    example: Maxime ad eius consequuntur.
                id:
                    type: integer
                    description: The unique id of the book.
                    example: 1784372645376317652
                    format: int64
                published_at:
                    type: string
                    description: The date at which the book was published.
                    example: Libero vitae voluptatem qui debitis.
                title:
                    type: string
                    description: The title of the book.
                    example: Aliquam et culpa sunt aut.
            example:
                author: Ullam sed sed.
                book_cover: Eaque ratione.
                id: 5311725847893351616
                published_at: Harum cum.
                title: Laboriosam fugit sequi facere error et.
            required:
                - id
                - title
                - book_cover
                - author
                - published_at
        Getbooksresponse:
            type: object
            properties:
                books:
                    $ref: '#/components/schemas/ResultbookCollection'
            example:
                books:
                    - author: Aut ut occaecati et et.
                      book_cover: Sed tenetur qui quisquam qui.
                      id: 3171323111833809843
                      published_at: Ratione sapiente et provident dolorum amet labore.
                      title: Et cumque velit ut quo ut.
                    - author: Aut ut occaecati et et.
                      book_cover: Sed tenetur qui quisquam qui.
                      id: 3171323111833809843
                      published_at: Ratione sapiente et provident dolorum amet labore.
                      title: Et cumque velit ut quo ut.
        Resultbook:
            type: object
            properties:
                author:
                    type: string
                    description: The author of the book.
                    example: Dolor ipsa pariatur est.
                book_cover:
                    type: string
                    description: The cover image of the book.
                    example: Tempora sequi aut et dolorem assumenda aut.
                id:
                    type: integer
                    description: The unique id of the book.
                    example: 9173575669321821314
                    format: int64
                published_at:
                    type: string
                    description: The date at which the book was published.
                    example: Omnis maiores.
                title:
                    type: string
                    description: The title of the book.
                    example: Et quo.
            example:
                author: Laudantium doloribus.
                book_cover: Excepturi odio ut animi consequatur.
                id: 5595262321692640013
                published_at: Culpa ratione consequatur est et dolorum tempora.
                title: Dolores esse non.
            required:
                - id
                - title
                - book_cover
                - author
                - published_at
        ResultbookCollection:
            type: array
            items:
                $ref: '#/components/schemas/Resultbook'
            example:
                - author: Aut ut occaecati et et.
                  book_cover: Sed tenetur qui quisquam qui.
                  id: 3171323111833809843
                  published_at: Ratione sapiente et provident dolorum amet labore.
                  title: Et cumque velit ut quo ut.
                - author: Aut ut occaecati et et.
                  book_cover: Sed tenetur qui quisquam qui.
                  id: 3171323111833809843
                  published_at: Ratione sapiente et provident dolorum amet labore.
                  title: Et cumque velit ut quo ut.
                - author: Aut ut occaecati et et.
                  book_cover: Sed tenetur qui quisquam qui.
                  id: 3171323111833809843
                  published_at: Ratione sapiente et provident dolorum amet labore.
                  title: Et cumque velit ut quo ut.
        UpdateBookRequestBody:
            type: object
            properties:
                author:
                    type: string
                    description: The author of the book.
                    example: dnd
                    minLength: 3
                    maxLength: 100
                book_cover:
                    type: string
                    description: The URL to the cover image.
                    example: i
                    minLength: 1
                    maxLength: 2048
                id:
                    type: integer
                    description: The unique id of the book.
                    example: 7264870070144899124
                    minimum: 1
                published_at:
                    type: string
                    description: The date at which the book was published.
                    example: "1984-05-06"
                    format: date
                title:
                    type: string
                    description: The title of the book.
                    example: j9
                    minLength: 1
                    maxLength: 255
            example:
                author: rff
                book_cover: xw
                id: 5357083602908013658
                published_at: "1983-03-06"
                title: d
            required:
                - title
                - author
                - book_cover
                - published_at
        Updatebookresponse:
            type: object
            properties:
                author:
                    type: string
                    description: The author of the book.
                    example: Est sunt.
                book_cover:
                    type: string
                    description: The cover image of the book.
                    example: Est eos culpa nihil quidem.
                id:
                    type: integer
                    description: The unique id of the book.
                    example: 8008908198875951311
                    format: int64
                published_at:
                    type: string
                    description: The date at which the book was published.
                    example: Nesciunt architecto aperiam non quia perferendis.
                title:
                    type: string
                    description: The title of the book.
                    example: Neque amet rerum explicabo deleniti possimus iste.
            example:
                author: Nesciunt incidunt reiciendis perspiciatis.
                book_cover: Sit dolorem nobis aperiam veniam veniam.
                id: 661423849706961713
                published_at: Qui quos omnis minima.
                title: Iure voluptatem cum quia expedita.
            required:
                - id
                - title
                - book_cover
                - author
                - published_at
tags:
    - name: librarian
      description: The books service performs CRUD operations on books.
